# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, upload_to='/home/ridwanfajar/Projects/my_projects/django/mini_hrd/assets/upload'),
        ),
    ]
